name: Node.js Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ["6.0"]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-port: 27017
          mongodb-db: test

      - name: Install dependencies
        run: npm ci

      - name: Wait for MongoDB and verify connection
        run: |
          echo "Waiting for MongoDB to be ready..."
          timeout 30 bash -c 'until mongosh --eval "db.runCommand({ping:1})" --quiet; do sleep 1; done'
          echo "MongoDB is ready!"

      - name: Run unit tests
        run: npm run test:unit
        env:
          NODE_ENV: test
          CONNECTION_STRING: mongodb://localhost:27017/test
          MONGODB_TIMEOUT: 30000
          MOCHA_TIMEOUT: 30000

      - name: Run integration tests
        run: npm run test:integration
        env:
          NODE_ENV: test
          CONNECTION_STRING: mongodb://localhost:27017/test
          MONGODB_TIMEOUT: 30000
          MOCHA_TIMEOUT: 30000

      - name: Run performance tests
        run: npm run test:performance
        env:
          NODE_ENV: test
          CONNECTION_STRING: mongodb://localhost:27017/test
          MONGODB_TIMEOUT: 30000
          MOCHA_TIMEOUT: 30000

      - name: Generate test coverage
        run: npm run test:coverage
        env:
          NODE_ENV: test
          CONNECTION_STRING: mongodb://localhost:27017/test
          MONGODB_TIMEOUT: 30000
          MOCHA_TIMEOUT: 30000

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7
